version: "3.7"

networks:
  server:
    name: server_network

services:
  chat-server:
    container_name: chat-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    restart: always
    networks:
      - server